// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS3l61cufaghPSEZOVY7Seh5H247bSbBM',
    appId: '1:291265351313:web:9a14c366d239b1e6faf930',
    messagingSenderId: '291265351313',
    projectId: 'web-hr-management',
    authDomain: 'web-hr-management.firebaseapp.com',
    storageBucket: 'web-hr-management.appspot.com',
    measurementId: 'G-6Z3PVFNJJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTI-a2cMVQYLQZsnGevyyEeVQA2RYwphA',
    appId: '1:291265351313:android:8a98ca2aca8398b7faf930',
    messagingSenderId: '291265351313',
    projectId: 'web-hr-management',
    storageBucket: 'web-hr-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCofhHHFozVfu0VOBlrd9M7ZdqTl2OKZCU',
    appId: '1:291265351313:ios:d7ce05bfc13b98d7faf930',
    messagingSenderId: '291265351313',
    projectId: 'web-hr-management',
    storageBucket: 'web-hr-management.appspot.com',
    iosBundleId: 'com.example.webHrManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCofhHHFozVfu0VOBlrd9M7ZdqTl2OKZCU',
    appId: '1:291265351313:ios:0621f822065b2d7ffaf930',
    messagingSenderId: '291265351313',
    projectId: 'web-hr-management',
    storageBucket: 'web-hr-management.appspot.com',
    iosBundleId: 'com.example.webHrManagement.RunnerTests',
  );
}
